

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - 'SECRET_KEY=django-insecure-mzm!dqy$$p1#&a8hk1_dp)w0riwjl6id6&!_8)=2i#71o#d@sve'
      - 'DEBUG=True'


  db:
    image: postgres:17.0
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
